version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: mobiusai-db
    environment:
      POSTGRES_DB: mobiusai
      POSTGRES_USER: mobiusai
      POSTGRES_PASSWORD: mobiusai123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mobiusai -d mobiusai"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MobiusAI Application
  app:
    build: .
    container_name: mobiusai-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://mobiusai:mobiusai123@postgres:5432/mobiusai
      - NODE_ENV=development
      - SESSION_SECRET=your-super-secret-session-key-min-32-chars
      - COOKIE_SECRET=your-cookie-secret-min-32-chars
      - OPENAI_API_KEY=your-openai-api-key
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
      - ./client/src:/app/client/src

volumes:
  postgres_data:
    driver: local 